PRJ_ROOT := $(CURDIR)
#PRJ_ROOT:= $(shell pwd)
include $(PRJ_ROOT)/make/defs.mak
include $(PRJ_ROOT)/make/rules.mak


#CURDIRECTORY := $(shell pwd)
#OBJS := helloworld.o
#test: VALUE := 1234
#test:
#	@echo "Value is $(VALUE)"

#echo:
#	@echo $(CURDIR)
#	@echo $(CURDIRECTORY)