FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN apt update && apt install -y \
    unminimize \
    man-db \
    manpages \
    manpages-dev \
    less \
    vim \
    git \
    sudo \
    curl

